# Generated by Django 5.2 on 2025-05-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='name',
        ),
    ]
