# Generated by Django 5.2 on 2025-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/Час'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Опис'),
        ),
    ]
